# Generated by Django 3.1.4 on 2020-12-06 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='date_of_birth',
            field=models.DateField(default=True),
        ),
    ]
