# Generated by Django 3.1.4 on 2020-12-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usuario_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
