# Generated by Django 3.1.4 on 2020-12-06 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
