# Generated by Django 3.1.4 on 2020-12-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201205_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='date_of_birth',
            field=models.DateField(verbose_name=0),
        ),
    ]
