# Generated by Django 3.1.4 on 2020-12-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_nome_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='funçao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
